<div class="container main">
    <div class="row">
        <div class="col-md-9">
            <h1>A Little Known Link</h1>
            <p class="text-right"><b>IIT Madras</b><br/>8 November 2016</p><br>
            <div class="row">
				<div class="col-md-2"></div>
				<div class="col-md-8 clear-paddings text-center">
					<img class='img-thumbnail' src='<?=STOCK_IMAGE_URL?>lfh/2016-11-08/0001.JPG' />
				</div>
				<div class="col-md-2"></div>
			</div>
			<p class="text-right"><a href="<?=BASE_URL?>describe/artefact/001_0024_IMG_0756_1" target="_blank">View in Archive</a></p>
			<p>We have at the Heritage Centre a row of panels devoted to the early convocations of IIT Madras. A visitor who studies these panels will observe that Nobel Laureate Dr. C.V. Raman was the chief speaker at the third convocation of the institute, held in 1966.</p>
			<p>The Heritage Centre also has in its photographic collection an album of pictures taken at this convocation. Some of these pictures were carried in an issue of <i>Campastimes</i>. And the first page of this issue was devoted entirely to the convocation. A team of four <i>Campastimes</i> reporters interviewed Dr. C.V. Raman at the Institute Guest House (now known as Bose&ndash;Einstein Guest House) before the convocation. They found him to be quite different from what they had expected him to be&mdash;&lsquo;joking and laughing most of the time, poking fun at everything from astrology to Dr. A.L. Mudaliar&rsquo;s turban&rsquo;. The Heritage Centre has a digital copy of this issue of <i>Campastimes</i> and has made it available online (Volume 4, No. 6 at https://heritage.iitm.ac.in/Publications).</p>
			<p>Early this year, I learnt something interesting about the talk that Dr. Raman delivered at the third convocation of IIT Madras. I was talking with Prof. V.G.K. Murti, retired faculty member of the Department of Electrical Engineering, who had joined the institute as an Assistant Professor in 1961. Prof. Murti recollected that Dr. Raman gave his speech without referring to</p>
			<p>any notes and that a printed copy of his address was not distributed at the convocation, as is normally done. Indeed, there are no sheets of paper in Dr. Raman&rsquo;s hand or on the table in front of him in the photograph showing him speaking. This was astonishing. Dr. Raman must have prepared extremely well to deliver his speech, or he must have delivered an impromptu talk&mdash;imagine, this at a convocation! Though Dr. Raman&rsquo;s address was not printed before the convocation, his talk was recorded, and the tape was available at the institute. In 1989, Prof. Murti made a transcript from the recording. I was keen to archive the transcript at the Heritage Centre. Prof. Murti promised to locate it and to send me a scanned image.</p>
			<p>Last week, an interesting sequence of events unfolded, as a result of which I discovered that there was another connection between IIT Madras and Dr. C.V. Raman, apart from the third convocation.</p>
			<p>A newspaper report was published online that spoke about <i>Campastimes</i>, about the coverage of the 1966 convocation in the magazine and, incidentally, about the Heritage Centre. Prof. Nagarajan, Dean International and Alumni Relations, brought the article to my attention and mailed the link to alumni groups.</p>
			<p>Among the alumni who got Prof. Nagarajan&rsquo;s mail was Mallik Putcha, who had received his M.Tech. certificate at that, the third, convocation. Mallik Putcha belongs to the very first batch of students of the institute. After obtaining his B.Tech. degree in 1964, he went on to enrol in the M.Tech. programme at IIT Madras the same year. The M.Tech. programme at the institute had begun only the previous year. Interestingly, M.Tech. degree certificates were not given to the first batch in the 1965 convocation, and the students of both the first and second M.Tech. batches received their certificates in 1966.</p>
			<p>Mallik, hawk-eyed, noted that the date on his M.Tech. certificate was two weeks later than the convocation date reported by the newspaper. He sent a query about this to me and to Prof. Nagarajan. He also wrote to two other alumni who had received degree certificates at the third convocation. One was Pasupathy, of the first M.Tech. batch, and the other was Subba, who received a B.Tech. degree at the 1966 convocation. While we are on the subject, Pasupathy also received the Siemens prize, from Dr. Raman, at the convocation. His prize was a set of books of his choice, pre-bought at IIT&rsquo;s suggestion for the occasion. As Dr. Raman was giving the prize, he asked Pasupathy &lsquo;Why is this so heavy?&rsquo;, surprising him.</p>
			<p>To find the answer to Mallik&rsquo;s question, I looked up the 1966 annual report of IIT Madras. Indeed, the newspaper had got the date wrong&mdash;the month was incorrect. Happy that the matter was settled, I proceeded to browse through the annual report. I had a pleasant surprise. I discovered that the text of Dr. Raman&rsquo;s speech had been printed in it! I lost no time in informing Prof. Murti about this discovery. Prof. Murti guessed that IIT Madras had, like him, transcribed Dr. Raman&rsquo;s speech from the recording. He thought that Dr. Raman must have edited the transcript.</p>
			<p>I read the text of Dr. Raman&rsquo;s talk, fascinated. It was a most inspiring and thought-provoking address.</p>
			<p>There are indications that at least parts of Dr. Raman&rsquo;s speech were extempore. &lsquo;I have been at many convocations but I have never seen an assembly that impressed me so much as the one that I am privileged to address now&rsquo;, he began. &lsquo;I have been on a joy-ride through the campus and was thrilled to see the wonderful, old banyan trees, the wild grass, the thorns here and there and the occasional buildings&rsquo;, he continued. Indeed, he referred to the trees again in his talk: &lsquo;&hellip;you have been subject to the influence of your teachers and also, I hope, of the old banyan trees around, which I do not regard as unimportant.&rsquo;</p>
			<p>The cheerfulness that the <i>Campastimes</i> reporters noted shows in the talk. &lsquo;I was privileged to be shaken by the hand by your prize-winners&mdash;hefty young fellows with plenty of grip in them&rsquo;, Dr. Raman said.</p>
			<p>He spoke about Germany and about attending a conference 10 years previously at a place called Lindau. &lsquo;This meeting was hosted by Count Bernadotte, and the minimum qualification for the invitee was that he should have won a Nobel Prize.&rsquo;1 Dr. Raman went on to the University of Freiburg in Breisgau and then to Bonn. &lsquo;Here I was enormously impressed by the Museum of Mineralogy and I marvelled at the way that a country so much devastated by the War could get together so swiftly such an amazing collection of rare and beautiful specimens.&rsquo;</p>
			<p>I was quite unprepared for what came next: &lsquo;By a coincidence, our Prime Minister, late Shri Jawaharlal Nehru, was also in Bonn at that time. We had lunch with the President of the German Republic. It was on this occasion that the German Government promised their gift of this Institute to India.&rsquo;</p>
			<p>It is well known that &lsquo;the seed of IIT Madras was sown in far-away German&rsquo;. But I had never heard that Dr. Raman was there at the historic meeting. It was truly exciting to unearth a little known but significant Raman&mdash;IIT Madras link.</p>
			<p class="text-right"><b>Kumaran Sathasivam</b></p>
			
			<hr><p><i>1 Once every year, 30 to 40 Nobel Laureates come to Lindau to meet the next generation of leading scientists, including Ph.D. students, undergraduates and post-doctoral researchers. The Lindau meetings began in 1951 (http://www.lindau-nobel.org/about/).</i></p>
        </div>
        <div class="col-md-3 sidebar">
			<?php require_once('application/views/generalSidebar.php');?>
        </div>
    </div>
</div>
